version: '3.2'

networks:
  alps:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    # build: ./containers/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - alps
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./containers/nginx/include.d:/etc/nginx/include.d
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./home/DocumentRoot:/var/www/html
      - ./var/log/nginx:/var/log/nginx

  php:
    container_name: php
    build: ./containers/php
    networks:
      - alps
    volumes:
      - ./home/DocumentRoot:/var/www/html

  php-xdebug:
    container_name: php-xdebug
    build: ./containers/php
    ports:
      - 9000:9000
    networks:
      - alps
    volumes:
      - ./home/DocumentRoot:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    networks:
      - alps
    volumes:
      - ./home/mysql:/var/lib/mysql
      - ./var/log/mysql:/var/log/mysql
